http://localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRiNjBiYmZkNjYzYjEzZjhhYWE3ZjYiLCJlbWFpbCI6InNhZXB1ZGluamVoMUBnbWFpbC5jb20iLCJpYXQiOjE2MDgyMzcyNjQsImV4cCI6MTYzOTc5NDg2NH0.q6b9pBsqYiovAUSTD9E3iBzaNr-s43NlX5cOBOui2js

###
POST http://localhost:5000/signup
Content-Type: application/json

{
    "email": "saepudinjeh@gmail.com",
    "password": "Agung-12345"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "saepudinjeh1@gmail.com",
    "password": "Agung-12345"
}


###
POST http://localhost:5000/refresh-token

###
DELETE http://localhost:5000/logout